
name: ml_project
dependencies:
  - python=3.12
  - pip
  - pip:
    - absl-py==2.1.0
    - aiohttp==3.9.5
    - aiosignal==1.3.1
    - altgraph==0.17.4
    - anyio==4.3.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - async-lru==2.0.4
    - attrs==23.2.0
    - Babel==2.15.0
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - category-encoders==2.6.3
    - certifi==2024.2.2
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - cloudpickle==3.0.0
    - colorama==0.4.6
    - comm==0.2.2
    - contourpy==1.2.1
    - cycler==0.12.1
    - datasets==2.19.0
    - debugpy==1.8.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - demoji==1.1.0
    - dill==0.3.8
    - executing==2.0.1
    - fastjsonschema==2.19.1
    - filelock==3.14.0
    - fonttools==4.51.0
    - fqdn==1.5.1
    - frozenlist==1.4.1
    - fsspec==2024.3.1
    - funcs==0.10.1
    - git-filter-repo==2.38.0
    - graphviz==0.20.3
    - grpcio==1.64.0
    - gym==0.26.2
    - gym-notices==0.0.8
    - h11==0.14.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - huggingface-hub==0.23.0
    - idna==3.7
    - iniconfig==2.0.0
    - intel-openmp==2021.4.0
    - ipykernel==6.29.4
    - ipython==8.24.0
    - ipywidgets==8.1.2
    - isoduration==20.11.0
    - jedi==0.19.1
    - Jinja2==3.1.3
    - joblib==1.4.2
    - json5==0.9.25
    - jsonpointer==2.4
    - jsonschema==4.22.0
    - jsonschema-specifications==2023.12.1
    - jupyter==1.0.0
    - jupyter-console==6.6.3
    - jupyter-events==0.10.0
    - jupyter-lsp==2.2.5
    - jupyter_client==8.6.1
    - jupyter_core==5.7.2
    - jupyter_server==2.14.0
    - jupyter_server_terminals==0.5.3
    - jupyterlab==4.1.8
    - jupyterlab_pygments==0.3.0
    - jupyterlab_server==2.27.1
    - jupyterlab_widgets==3.0.10
    - kiwisolver==1.4.5
    - lightning-utilities==0.11.2
    - littleutils==0.2.2
    - Markdown==3.6
    - MarkupSafe==2.1.5
    - matplotlib==3.8.4
    - matplotlib-inline==0.1.7
    - mistune==3.0.2
    - mkl==2021.4.0
    - mpmath==1.3.0
    - multidict==6.0.5
    - multiprocess==0.70.16
    - mysql-connector-python==8.3.0
    - named==1.4.2
    - nbclient==0.10.0
    - nbconvert==7.16.4
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==3.3
    - notebook==7.1.3
    - notebook_shim==0.2.4
    - numpy==1.26.4
    - nvidia-smi==0.1.3
    - overrides==7.7.0
    - packaging==24.0
    - pandas==2.2.2
    - pandocfilters==1.5.1
    - parso==0.8.4
    - patsy==0.5.6
    - pefile==2023.2.7
    - pillow==10.3.0
    - platformdirs==4.2.1
    - pluggy==1.5.0
    - prometheus_client==0.20.0
    - prompt-toolkit==3.0.43
    - protobuf==5.27.0
    - psutil==5.9.8
    - pure-eval==0.2.2
    - pyarrow==16.0.0
    - pyarrow-hotfix==0.6
    - pycparser==2.22
    - Pygments==2.18.0
    - pyinstaller==6.7.0
    - pyinstaller-hooks-contrib==2024.6
    - pyparsing==3.1.2
    - pytest==8.2.1
    - python-dateutil==2.9.0.post0
    - python-json-logger==2.0.7
    - pytorch-lightning==2.3.0
    - pytz==2024.1
    - pywin32==306
    - pywin32-ctypes==0.2.2
    - pywinpty==2.0.13
    - PyYAML==6.0.1
    - pyzmq==26.0.3
    - qtconsole==5.5.2
    - QtPy==2.4.1
    - referencing==0.35.1
    - requests==2.31.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.18.1
    - scikit-learn==1.4.2
    - scipy==1.13.0
    - seaborn==0.13.2
    - Send2Trash==1.8.3
    - setuptools==70.0.0
    - six==1.16.0
    - sniffio==1.3.1
    - solus==1.2.2
    - sorcery==0.2.2
    - soupsieve==2.5
    - stack-data==0.6.3
    - statsmodels==0.14.2
    - sympy==1.12
    - tbb==2021.12.0
    - tensorboard==2.16.2
    - tensorboard-data-server==0.7.2
    - terminado==0.18.1
    - threadpoolctl==3.5.0
    - tinycss2==1.3.0
    - tkcalendar==1.6.1
    - torch==2.3.0+cu121
    - torchaudio==2.3.0+cu121
    - torchmetrics==1.4.0.post0
    - torchsummary==1.5.1
    - torchtext==0.18.0
    - torchvision==0.18.0
    - tornado==6.4
    - tqdm==4.66.4
    - traitlets==5.14.3
    - types-python-dateutil==2.9.0.20240316
    - typing-aliases==1.10.1
    - typing_extensions==4.11.0
    - tzdata==2024.1
    - ucimlrepo==0.0.6
    - Unidecode==1.3.8
    - uri-template==1.3.0
    - urllib3==2.2.1
    - wcwidth==0.2.13
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - Werkzeug==3.0.3
    - widgetsnbextension==4.0.10
    - wrapt==1.16.0
    - xxhash==3.4.1
    - yarl==1.9.4
